from __future__ import annotations


EXPANDED_SEED_ARTICLES: list[dict[str, object]] = [
    {
        "slug": "nimh-depression-basics",
        "title": "抑郁有哪些常见信号",
        "category": "emotion",
        "audience": "all",
        "summary_30s": "抑郁不只是心情不好，常见信号包括持续低落、兴趣下降、精力变差、睡眠食欲变化、自责无望，严重时会出现死亡或自伤想法。",
        "explanation_3min": "抑郁相关症状通常会同时影响情绪、身体、想法和日常功能。你可能发现自己对原本喜欢的事失去兴趣，变得很疲惫、难以集中，睡太多或睡不着，吃得明显变多或变少，也可能反复觉得自己没用。一次低落不等于抑郁障碍，是否需要诊断要由专业人员结合持续时间、症状数量和功能受损来判断。",
        "advanced_text": "NIMH 资料指出，抑郁治疗通常包括心理治疗、药物或两者结合；具体方案应由专业人员结合个人情况决定。",
        "common_misunderstandings": ["抑郁不是单纯懒或不够坚强。", "只有几个症状也可能值得寻求支持，不必等到完全撑不住。"],
        "actions": ["先记录最近两周的睡眠、食欲、兴趣和精力变化。", "把今天任务降到一个最小可完成动作。", "联系可信任的人，说明自己最近状态明显变差。"],
        "seek_help_when": ["低落或兴趣下降持续影响学习、工作、关系或基本生活。", "出现死亡、自伤、自杀想法或计划。", "你需要判断是否达到抑郁障碍标准或是否需要治疗。"],
        "tags": ["抑郁", "低落", "兴趣下降", "无望", "求助"],
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/depression",
        "license": "public-domain-text",
    },
    {
        "slug": "nimh-stress-vs-anxiety",
        "title": "压力和焦虑有什么不同",
        "category": "stress",
        "audience": "all",
        "summary_30s": "压力通常和外部事件有关，焦虑更像身体对压力或威胁的持续警报；两者都可能影响睡眠、身体和注意力。",
        "explanation_3min": "压力常来自考试、工作、人际冲突或生活变化，事情解决后可能缓解。焦虑则可能在没有明确威胁时仍持续存在，表现为担心、紧绷、坐立不安、睡不着或身体不舒服。区分两者的关键不是给自己贴标签，而是看触发源、持续时间、是否开始回避，以及是否影响日常生活。",
        "advanced_text": "NIMH 建议通过识别压力源、保持规律睡眠和饮食、运动、写日记、放松练习、挑战无帮助想法和寻求支持来应对压力与焦虑。",
        "common_misunderstandings": ["有压力不代表你能力差。", "焦虑不是一定要有现实危险才会出现。"],
        "actions": ["写下当前最主要的外部压力源和最强烈的担心。", "先做一个能降低压力的现实小动作。", "减少过量咖啡因，尽量维持基本睡眠节律。"],
        "seek_help_when": ["压力或焦虑开始让你回避重要事情。", "症状持续存在并影响生活。", "出现自伤想法、强烈失控感或现实安全风险。"],
        "tags": ["压力", "焦虑", "压力源", "担心", "睡眠"],
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/stress/index.shtml",
        "license": "public-domain-text",
    },
    {
        "slug": "nimh-ocd-basics",
        "title": "OCD 和强迫症是什么",
        "category": "emotion",
        "audience": "all",
        "summary_30s": "OCD 通常指强迫症，核心是反复出现的侵入性想法、冲动或画面，以及为了缓解焦虑而重复进行的行为或心理动作。",
        "explanation_3min": "强迫思维常让人觉得这些想法很烦、很吓人或不符合自己，但越想摆脱越容易被卡住。强迫行为可能包括反复检查、清洗、确认、计数，或在脑中重复某些步骤。偶尔爱整洁不等于强迫症；关键要看这些循环是否耗时、痛苦，并影响学习、工作、关系或生活。",
        "advanced_text": "NIMH 资料提到，暴露与反应预防 ERP 是 CBT 的一种形式，常用于减少强迫行为；是否适合需要专业评估。",
        "common_misunderstandings": ["强迫症不是简单爱干净。", "有侵入性想法不等于你真的想那样做。"],
        "actions": ["先区分：这是侵入性想法，还是我真正的意愿。", "记录触发场景、焦虑峰值和重复行为。", "避免独自强行暴露到无法承受，优先寻求专业指导。"],
        "seek_help_when": ["反复检查、清洗或确认每天耗费很多时间。", "你因为强迫循环明显痛苦或功能受损。", "强迫内容涉及自伤、伤人或现实安全风险。"],
        "tags": ["OCD", "强迫症", "强迫", "侵入性想法", "ERP", "CBT"],
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/obsessive-compulsive-disorder-when-unwanted-thoughts-or-repetitive-behaviors-take-over",
        "license": "public-domain-text",
    },
    {
        "slug": "nimh-adhd-basics",
        "title": "ADHD 是什么",
        "category": "self_help",
        "audience": "all",
        "summary_30s": "ADHD 是注意缺陷多动障碍，常见表现是持续的注意力困难、多动或冲动，并且会影响学习、工作、关系或日常管理。",
        "explanation_3min": "ADHD 不只是偶尔分心，也不是单纯不自律。它通常从儿童期开始，可能表现为难以维持注意、拖延和丢三落四，也可能表现为坐不住、话多、冲动决定。成年人也可能受影响。睡眠问题、焦虑、抑郁和身体疾病也会造成类似表现，所以不能只靠网上描述自我诊断。",
        "advanced_text": "NIMH 资料说明，ADHD 评估通常会了解多个场景中的表现，并可能使用标准化量表；治疗可包括药物、心理治疗、行为干预和学校/工作支持。",
        "common_misunderstandings": ["ADHD 不是懒或故意不听话。", "高功能或成绩不错也不代表一定没有 ADHD。"],
        "actions": ["记录注意力、拖延、冲动和时间管理问题出现在哪些场景。", "把任务拆到 10-15 分钟并减少环境干扰。", "如果长期影响生活，考虑做专业评估。"],
        "seek_help_when": ["注意力或冲动问题长期影响学习、工作或关系。", "你怀疑症状从小就存在并跨多个场景出现。", "合并焦虑、抑郁、睡眠问题或风险行为。"],
        "tags": ["ADHD", "注意缺陷多动", "注意力", "冲动", "执行功能"],
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/attention-deficit-hyperactivity-disorder-what-you-need-to-know",
        "license": "public-domain-text",
    },
    {
        "slug": "medlineplus-bipolar-basics",
        "title": "双相情感障碍是什么",
        "category": "emotion",
        "audience": "all",
        "summary_30s": "双相情感障碍是一类心境障碍，会出现明显的情绪、精力和活动水平波动，包括躁狂或轻躁狂阶段，也可能有抑郁阶段。",
        "explanation_3min": "双相不是普通心情忽好忽坏。躁狂或轻躁狂阶段可能表现为睡得很少却精力很高、话多、冲动消费、冒险行为、思维飞快或异常自信；抑郁阶段则可能低落、无望、精力差、兴趣下降。是否属于双相需要专业评估，尤其要区分焦虑、抑郁、ADHD、物质影响和睡眠不足等因素。",
        "advanced_text": "MedlinePlus 资料强调，双相障碍会造成情绪、行为、精力和活动水平变化；诊断和治疗应由医生或心理健康专业人员进行。",
        "common_misunderstandings": ["情绪波动不一定就是双相。", "双相不能只按抑郁处理，躁狂或轻躁狂线索很重要。"],
        "actions": ["记录睡眠时长、精力、消费/冒险行为和情绪变化。", "如果怀疑轻躁或躁狂，不要自行停药或自行用药。", "把异常兴奋和异常低落都告诉专业人员。"],
        "seek_help_when": ["几乎不睡也精力很高，并伴随冲动或冒险行为。", "情绪波动严重影响生活或关系。", "出现自伤、自杀想法或失控行为。"],
        "tags": ["双相", "躁郁", "躁狂", "轻躁狂", "抑郁"],
        "source_key": "medlineplus_public_domain",
        "source_url": "https://medlineplus.gov/bipolardisorder.html",
        "license": "public-domain-health-topic-summaries",
    },
    {
        "slug": "nimh-eating-disorders-basics",
        "title": "饮食障碍有哪些常见警讯",
        "category": "self_help",
        "audience": "all",
        "summary_30s": "饮食障碍是严重疾病，可能表现为极端限制进食、暴食、催吐或过度运动，也可能和体重、体型、食物控制强烈纠缠。",
        "explanation_3min": "饮食障碍不只是挑食或爱美，而是饮食行为、身体形象和控制感出现严重困扰。常见类型包括神经性厌食、神经性贪食、暴食障碍和回避限制性食物摄入障碍。它可能影响身体健康，也常和焦虑、抑郁、羞耻或自我价值感问题交织，需要医学、营养和心理支持共同处理。",
        "advanced_text": "NIMH 资料指出，饮食障碍可能危及生命；早期识别和治疗很重要，治疗通常包括心理治疗、医疗监测和营养支持。",
        "common_misunderstandings": ["体重看起来正常也可能有饮食障碍。", "饮食障碍不是靠意志力就能解决。"],
        "actions": ["记录限制、暴食、催吐、过度运动或体重检查的频率。", "避免把饮食问题只当成自律问题。", "尽早联系医生或心理健康专业人员评估。"],
        "seek_help_when": ["进食、体重或体型想法已经支配大部分生活。", "出现催吐、滥用泻药、极端节食或过度运动。", "体重快速变化、晕厥、胸闷或出现自伤想法。"],
        "tags": ["饮食障碍", "暴食", "厌食", "贪食", "身体形象"],
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/eating-disorders",
        "license": "public-domain-text",
    },
    {
        "slug": "medlineplus-insomnia-basics",
        "title": "失眠和睡不好有什么区别",
        "category": "sleep",
        "audience": "all",
        "summary_30s": "失眠通常指入睡困难、睡不稳、醒得太早或睡醒仍不恢复，并且影响白天状态。",
        "explanation_3min": "偶尔睡不好很常见，但如果睡眠问题反复出现，并影响白天注意力、情绪、学习或工作，就需要认真处理。压力、焦虑、作息不规律、咖啡因、身体疾病、药物和环境都可能影响睡眠。处理失眠不只是早点躺下，更重要的是稳定作息、降低睡前唤醒，并排查持续存在的压力或健康因素。",
        "advanced_text": "MedlinePlus 将失眠描述为常见睡眠障碍；持续失眠需要由医疗人员评估原因和处理方式。",
        "common_misunderstandings": ["躺得越久不一定睡得越好。", "长期失眠不只是意志力或自律问题。"],
        "actions": ["固定起床时间，减少白天长时间补觉。", "睡前减少高刺激内容和咖啡因。", "把担心写到纸上，安排到第二天处理。"],
        "seek_help_when": ["睡眠问题持续影响白天功能。", "伴随强烈焦虑、低落、惊恐或创伤反应。", "需要判断是否有身体疾病、药物或其他睡眠障碍影响。"],
        "tags": ["失眠", "睡不着", "睡眠", "入睡困难", "早醒"],
        "source_key": "medlineplus_public_domain",
        "source_url": "https://medlineplus.gov/insomnia.html",
        "license": "public-domain-health-topic-summaries",
    },
    {
        "slug": "nimh-borderline-personality-basics",
        "title": "边缘型人格障碍有哪些核心特征",
        "category": "relationship",
        "audience": "all",
        "summary_30s": "边缘型人格障碍通常涉及强烈情绪波动、害怕被抛下、不稳定关系、自我感不稳定、冲动和自伤风险，但需要专业评估。",
        "explanation_3min": "边缘型人格障碍不是用来骂人的标签。它描述的是一组长期困扰：情绪来得很强、关系容易从很近到很远、对拒绝或抛弃特别敏感，也可能出现空虚感、解离、冲动行为或自伤。很多症状会和创伤、抑郁、双相、焦虑或 ADHD 重叠，所以不适合靠单个表现自我诊断。",
        "advanced_text": "NIMH 资料指出，心理治疗是边缘型人格障碍的一线治疗；DBT 可帮助调节强烈情绪、减少自毁行为并改善关系。",
        "common_misunderstandings": ["边缘型人格障碍不是人品差。", "强烈情绪和关系痛苦可以被理解和治疗。"],
        "actions": ["把触发点、情绪峰值和冲动行为记录下来。", "先练习暂停和稳定身体，再处理关系冲突。", "如果长期反复出现这些模式，寻找有经验的专业支持。"],
        "seek_help_when": ["出现自伤、自杀想法或冲动行为。", "关系冲突和情绪波动长期影响生活。", "你需要区分边缘型人格、双相、创伤或其他问题。"],
        "tags": ["边缘型人格障碍", "BPD", "情绪调节", "关系", "DBT", "解离"],
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/borderline-personality-disorder",
        "license": "public-domain-text",
    },
    {
        "slug": "nimh-when-to-get-mental-help",
        "title": "心理状态什么时候需要求助",
        "category": "safety",
        "audience": "all",
        "summary_30s": "当情绪、睡眠、行为或想法持续恶化，影响生活，或出现自伤自杀想法时，就应该优先联系现实支持和专业帮助。",
        "explanation_3min": "自助方法有时能缓解压力，但如果症状变重、持续不退，或你开始无法完成学习工作、维持关系和照顾自己，就不适合继续独自扛。求助可以从可信任的人、学校心理老师、心理咨询师、精神科医生或当地危机资源开始。紧急风险下，现实安全要先于知识问答。",
        "advanced_text": "NIMH 建议，如果自助活动无效或症状加重，应联系医疗或心理健康专业人员。",
        "common_misunderstandings": ["求助不是失败。", "不需要等到危机才可以找专业人员。"],
        "actions": ["把最近最影响生活的三个变化写下来。", "选一个现实中的人说明你需要支持。", "预约医生、咨询师或学校心理资源。"],
        "seek_help_when": ["出现自伤、自杀想法或无法保证安全。", "情绪、睡眠或行为问题持续影响基本生活。", "自助方法无效，症状正在加重。"],
        "tags": ["求助", "心理健康", "专业帮助", "危机", "现实支持"],
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/my-mental-health-do-i-need-help",
        "license": "public-domain-text",
    },
]


BULK_SOURCE_PROFILES: dict[str, dict[str, str]] = {
    "nimh_depression": {
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/depression",
        "license": "public-domain-text",
        "source_note": "NIMH 抑郁资料强调，抑郁会影响情绪、身体、认知和功能，治疗方案需由专业人员结合个人情况决定。",
    },
    "nimh_stress": {
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/stress/index.shtml",
        "license": "public-domain-text",
        "source_note": "NIMH 压力资料区分压力和焦虑，并建议通过睡眠、运动、支持和识别无帮助想法来应对。",
    },
    "nimh_gad": {
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/generalized-anxiety-disorder-gad",
        "license": "public-domain-text",
        "source_note": "NIMH 广泛性焦虑资料强调，持续、难以控制的担心如果影响生活，应考虑专业评估。",
    },
    "nimh_social_anxiety": {
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/social-anxiety-disorder-more-than-just-shyness",
        "license": "public-domain-text",
        "source_note": "NIMH 社交焦虑资料指出，害怕被评价和回避社交场景若持续影响生活，可能需要治疗支持。",
    },
    "nimh_panic": {
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/panic-disorder-when-fear-overwhelms",
        "license": "public-domain-text",
        "source_note": "NIMH 惊恐障碍资料说明，惊恐发作会出现强烈恐惧和身体警报，但可通过专业治疗改善。",
    },
    "medlineplus_phobias": {
        "source_key": "medlineplus_public_domain",
        "source_url": "https://medlineplus.gov/phobias.html",
        "license": "public-domain-health-topic-summaries",
        "source_note": "MedlinePlus 恐惧症资料将恐惧症描述为对特定对象或场景的强烈、持续恐惧和回避。",
    },
    "nimh_ocd": {
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/obsessive-compulsive-disorder-when-unwanted-thoughts-or-repetitive-behaviors-take-over",
        "license": "public-domain-text",
        "source_note": "NIMH OCD 资料强调强迫思维和强迫行为可造成显著痛苦，ERP 是常见的循证治疗方向之一。",
    },
    "nimh_adhd": {
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/attention-deficit-hyperactivity-disorder-what-you-need-to-know",
        "license": "public-domain-text",
        "source_note": "NIMH ADHD 资料强调注意力、多动和冲动症状需要跨场景、持续性和功能影响评估。",
    },
    "nimh_ptsd": {
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/post-traumatic-stress-disorder-ptsd",
        "license": "public-domain-text",
        "source_note": "NIMH PTSD 资料将症状分为再体验、回避、警觉反应和认知情绪变化，并强调专业创伤支持。",
    },
    "medlineplus_insomnia": {
        "source_key": "medlineplus_public_domain",
        "source_url": "https://medlineplus.gov/insomnia.html",
        "license": "public-domain-health-topic-summaries",
        "source_note": "MedlinePlus 失眠资料指出，持续入睡困难、睡眠维持困难或早醒若影响白天功能，需要评估原因。",
    },
    "nimh_help": {
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/my-mental-health-do-i-need-help",
        "license": "public-domain-text",
        "source_note": "NIMH 求助资料建议，如果症状持续、加重或影响生活，应联系医疗或心理健康专业人员。",
    },
    "nimh_bpd": {
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/borderline-personality-disorder",
        "license": "public-domain-text",
        "source_note": "NIMH 边缘型人格障碍资料强调情绪调节、关系不稳定、冲动和自伤风险需要专业评估和治疗。",
    },
    "nimh_eating": {
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/eating-disorders",
        "license": "public-domain-text",
        "source_note": "NIMH 饮食障碍资料强调饮食障碍是严重疾病，可能影响身体和心理健康，早期治疗很重要。",
    },
    "nimh_psychosis": {
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/topics/schizophrenia/raise/what-is-psychosis",
        "license": "public-domain-text",
        "source_note": "NIMH 精神病性症状资料指出，精神病性体验涉及与现实接触受损，早期专业支持很重要。",
    },
    "nimh_schizophrenia": {
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/schizophrenia",
        "license": "public-domain-text",
        "source_note": "NIMH 精神分裂症资料强调幻觉、妄想、思维紊乱、动机下降和认知困难等症状需要综合治疗。",
    },
    "nimh_autism": {
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/autism-spectrum-disorder",
        "license": "public-domain-text",
        "source_note": "NIMH 自闭谱系资料指出，ASD 涉及社会沟通、限制性兴趣和重复行为，并呈现广泛个体差异。",
    },
    "nimh_suicide": {
        "source_key": "nimh_public_domain",
        "source_url": "https://www.nimh.nih.gov/health/publications/warning-signs-of-suicide",
        "license": "public-domain-text",
        "source_note": "NIMH 自杀预警资料强调，谈论死亡、绝望、计划方法、告别或行为突变等信号需要尽快求助。",
    },
}


BULK_TOPIC_GROUPS: tuple[dict[str, object], ...] = (
    {
        "source": "nimh_depression",
        "category": "emotion",
        "actions": ["记录最近两周情绪、睡眠、食欲和兴趣变化。", "把今天任务降到一个最小可完成动作。", "联系可信任的人说明状态变差。"],
        "seek_help_when": ["低落或兴趣下降持续影响学习、工作或关系。", "出现死亡、自伤或自杀想法。", "你需要判断是否需要专业治疗。"],
        "tags": ["抑郁", "低落", "兴趣下降", "求助"],
        "topics": (
            ("bulk-depression-anhedonia", "对什么都没兴趣可能意味着什么", "兴趣下降是抑郁相关的重要信号之一，但也可能和压力、疲惫或生活变化有关。", "如果原本喜欢的事持续变得没有吸引力，并伴随低落、疲惫或功能下降，需要认真观察。"),
            ("bulk-depression-fatigue", "长期没力气和抑郁有什么关系", "抑郁可能让人感到疲惫、迟缓和恢复不过来，不一定只是睡少或懒。", "精力下降如果持续存在，并影响基本任务，适合同时关注情绪、睡眠和身体健康因素。"),
            ("bulk-depression-concentration", "抑郁时为什么很难集中注意力", "抑郁常会影响注意、记忆和决策，让简单任务也变得费劲。", "当大脑像变慢一样，先减少任务负荷，比强迫自己高效更现实。"),
            ("bulk-depression-guilt", "强烈自责和无价值感需要注意什么", "持续的内疚、无价值感或自我否定可能是抑郁相关信号。", "这类想法很有说服力，但不等于事实；如果反复出现，应考虑寻求支持。"),
            ("bulk-depression-irritability", "抑郁也可能表现为易怒吗", "抑郁不一定只表现为哭或悲伤，也可能表现为烦躁、易怒和低耐受。", "当易怒背后伴随疲惫、兴趣下降或无望感，需要从情绪状态整体理解。"),
            ("bulk-depression-sleep-appetite", "睡眠食欲变化和抑郁的关系", "睡太多、睡不着、早醒、食欲明显变化都可能出现在抑郁相关状态中。", "单个变化不等于诊断，但多个变化持续出现时值得记录和求助。"),
            ("bulk-depression-physical-pain", "抑郁会带来身体不舒服吗", "抑郁有时会伴随头痛、胃肠不适、身体疼痛或沉重感。", "身体症状需要排除医学原因，也要留意它们是否和情绪、压力同步变化。"),
            ("bulk-depression-teen-signs", "青少年抑郁可能有哪些表现", "青少年抑郁可能表现为低落、易怒、退缩、成绩下滑、睡眠变化或自我否定。", "青少年出现持续功能下降或安全风险时，应优先联系家长、老师或专业人员。"),
            ("bulk-depression-helping-friend", "看到朋友疑似抑郁可以怎么做", "支持疑似抑郁的人时，稳定陪伴和鼓励专业求助比简单劝开心更有帮助。", "可以表达关心、倾听具体困难，并在安全风险出现时联系现实支持。"),
            ("bulk-depression-relapse-warning", "抑郁状态反复前有哪些预警", "睡眠变乱、兴趣下降、回避社交、自责增加可能是状态反复的早期信号。", "提前识别预警信号，有助于尽早恢复支持和降低风险。"),
        ),
    },
    {
        "source": "nimh_gad",
        "category": "stress",
        "actions": ["写下最常反复担心的主题。", "区分可行动问题和暂时无法控制的问题。", "先做一个降低身体紧绷的小动作。"],
        "seek_help_when": ["担心难以控制并持续影响生活。", "因为焦虑开始回避重要场景。", "伴随惊恐、自伤想法或明显功能受损。"],
        "tags": ["焦虑", "担心", "压力", "身体紧绷"],
        "topics": (
            ("bulk-anxiety-gad-worry", "总是担心很多事是广泛性焦虑吗", "长期、难以控制地担心许多生活主题，可能和广泛性焦虑有关。", "是否达到障碍标准需要看持续时间、控制难度和功能影响。"),
            ("bulk-anxiety-body-symptoms", "焦虑为什么会有身体反应", "焦虑会激活身体警报系统，带来心跳、肌肉紧绷、胃部不适或出汗等反应。", "身体反应是真实的，但不一定意味着马上有危险。"),
            ("bulk-anxiety-avoidance-cycle", "越躲越怕是怎么回事", "回避能短暂降低焦虑，但长期可能让大脑更确信场景很危险。", "安全前提下逐步面对，比一次逼自己硬扛更稳。"),
            ("bulk-anxiety-caffeine", "咖啡因会放大焦虑吗", "咖啡因可能让心跳、紧张和睡眠问题更明显，从而放大焦虑体验。", "如果焦虑和心慌明显，可以观察咖啡、能量饮料和浓茶摄入。"),
            ("bulk-anxiety-uncertainty", "为什么不确定性让人特别焦虑", "焦虑常把未知当作需要马上排除的风险，于是不断确认和预演。", "练习容纳一点不确定性，是降低焦虑循环的一个方向。"),
            ("bulk-anxiety-worry-time", "担忧时段有什么用", "把担心集中到固定时段，可以减少全天反复陷入同一问题。", "担忧时段不是压抑问题，而是给大脑一个可预测的处理窗口。"),
            ("bulk-anxiety-muscle-tension", "焦虑和肌肉紧绷有什么关系", "持续焦虑会让身体长期处于准备应对状态，肩颈、胸口和下颌更容易紧。", "放松训练、呼气延长和活动身体可以帮助降低唤醒。"),
            ("bulk-anxiety-reassurance", "反复确认为什么停不下来", "反复确认能暂时安心，但也会让不确定性变得更难承受。", "可以逐步延迟确认时间，并记录焦虑自然下降的过程。"),
            ("bulk-anxiety-work-stress", "工作压力很大时先处理什么", "工作压力下先区分任务负荷、关系压力和自我要求，有助于找到入口。", "先减少一个可控负荷，比要求自己立刻不焦虑更实际。"),
            ("bulk-anxiety-stress-vs-disorder", "普通焦虑和焦虑障碍怎么区分", "普通焦虑会随压力变化，而焦虑障碍更可能持续、难控制并影响生活。", "判断重点是持续时间、回避程度和功能受损，而不是是否紧张。"),
        ),
    },
    {
        "source": "nimh_social_anxiety",
        "category": "relationship",
        "actions": ["选一个低风险社交动作练习。", "记录担心被评价的具体想法。", "结束后只复盘事实，不做羞辱式评价。"],
        "seek_help_when": ["回避社交影响学习、工作或关系。", "社交焦虑持续数月且难以缓解。", "社交后强烈自责或出现自伤想法。"],
        "tags": ["社交焦虑", "评价恐惧", "回避", "CBT"],
        "topics": (
            ("bulk-social-anxiety-basics", "社交焦虑不只是害羞", "社交焦虑是对被评价、出丑或被拒绝的强烈害怕，可能影响日常活动。", "害羞不一定需要治疗，但持续回避和功能受损需要认真处理。"),
            ("bulk-social-anxiety-performance", "上台或发言前特别害怕怎么办", "表现型社交焦虑常集中在演讲、回答问题、面试或表演场景。", "可以从小剂量练习和身体稳定开始，而不是要求自己完全不紧张。"),
            ("bulk-social-anxiety-eye-contact", "不敢对视说明什么", "不敢对视可能和社交焦虑、自我监控或担心被看穿有关。", "可以先练习短暂看向眉心或鼻梁，逐步降低回避。"),
            ("bulk-social-anxiety-after-review", "社交后反复复盘很痛苦怎么办", "社交后反复找错误会强化评价恐惧，让下一次社交更难。", "复盘时只记录事实和一个可改进点，避免羞辱自己。"),
            ("bulk-social-anxiety-school", "学生害怕上课发言怎么办", "课堂发言焦虑可能和被同学评价、答错或身体反应被看见有关。", "可以先从提前准备一句话、低风险提问或课后沟通开始。"),
            ("bulk-social-anxiety-dating", "约会时特别紧张是社交焦虑吗", "约会场景容易激活被评价和被拒绝的担心。", "如果紧张让你长期回避关系或严重痛苦，可以从社交焦虑角度理解。"),
            ("bulk-social-anxiety-avoidance", "社交焦虑为什么越躲越严重", "回避能暂时减轻紧张，但会减少大脑学习安全经验的机会。", "逐步、可控地接触社交场景，比突然挑战高难度更稳。"),
            ("bulk-social-anxiety-support-groups", "社交焦虑支持小组有用吗", "支持小组能提供练习和反馈，但不能替代专业治疗建议。", "选择支持小组时要注意安全边界和信息质量。"),
            ("bulk-social-anxiety-physical", "社交时脸红手抖怎么办", "脸红、出汗、手抖和心跳快是焦虑身体反应，不代表你表现失败。", "先降低对身体反应的灾难化，往往比强行压住更有效。"),
            ("bulk-social-anxiety-help-loved-one", "怎么支持社交焦虑的朋友", "支持社交焦虑的人时，理解和陪伴比嘲笑或强推社交更有效。", "可以一起拆小目标，但不要替对方做所有决定。"),
        ),
    },
    {
        "source": "nimh_panic",
        "category": "emotion",
        "actions": ["把注意力放到呼气和脚底触地。", "提醒自己这是身体警报，峰值会过去。", "记录发作前的睡眠、咖啡因和压力。"],
        "seek_help_when": ["惊恐反复出现并导致回避。", "症状像急性身体疾病或你无法判断安全。", "伴随自伤想法或强烈失控。"],
        "tags": ["惊恐", "心慌", "身体警报", "呼吸"],
        "topics": (
            ("bulk-panic-attack-signs", "惊恐发作有哪些常见表现", "惊恐发作会突然出现强烈恐惧，伴随心跳快、胸闷、发抖或濒死感。", "这些感觉很吓人，但常见机制是身体警报被强烈激活。"),
            ("bulk-panic-heart-attack-fear", "惊恐时总怕心脏出事怎么办", "惊恐发作可能让人误以为心脏出问题，尤其是胸闷和心跳明显时。", "第一次出现或症状异常应排除医学风险，反复发作可做心理评估。"),
            ("bulk-panic-breathing", "惊恐时呼吸越乱怎么办", "惊恐时呼吸急促会加重头晕、麻木和失控感。", "把呼气拉长、减少过度换气，有助于降低身体警报。"),
            ("bulk-panic-derealization", "惊恐时觉得不真实正常吗", "惊恐或强焦虑时可能出现不真实感、抽离感或像隔着玻璃看世界。", "这通常和高唤醒有关，但反复强烈出现时需要专业评估。"),
            ("bulk-panic-avoidance", "怕再次惊恐所以不敢出门怎么办", "对下一次发作的害怕可能让人回避交通、商场或独处。", "回避扩大时，最好寻求专业支持做循序渐进的恢复。"),
            ("bulk-panic-caffeine-sleep", "睡少和咖啡会诱发惊恐吗", "睡眠不足和咖啡因可能放大心跳、紧张和身体敏感度。", "记录这些因素有助于识别可调整的触发点。"),
            ("bulk-panic-aftercare", "惊恐发作后应该怎么恢复", "发作后身体可能很累，也可能担心下一次再来。", "先补水、休息、记录诱因，再决定是否需要专业帮助。"),
            ("bulk-panic-disorder", "惊恐发作和惊恐障碍有什么区别", "一次惊恐发作不等于惊恐障碍，关键是反复发作和持续担心、回避。", "如果生活被怕发作限制，就需要更系统地处理。"),
            ("bulk-panic-helping-someone", "别人惊恐发作时怎么陪", "陪伴惊恐中的人时，稳定、简短和不责备很重要。", "可以提醒对方慢慢呼气、坐稳、观察环境，必要时联系医疗帮助。"),
            ("bulk-panic-treatment", "惊恐障碍可以治疗吗", "惊恐相关问题可通过 CBT、暴露练习和必要时药物等方式改善。", "具体治疗应由专业人员结合个人情况制定。"),
        ),
    },
    {
        "source": "nimh_ocd",
        "category": "self_help",
        "actions": ["记录强迫想法、焦虑峰值和重复行为。", "练习把想法命名为侵入性想法。", "避免独自做高强度暴露，优先专业指导。"],
        "seek_help_when": ["强迫循环每天耗费大量时间。", "重复行为明显影响生活。", "强迫内容涉及自伤、伤人或安全风险。"],
        "tags": ["OCD", "强迫症", "侵入性想法", "ERP"],
        "topics": (
            ("bulk-ocd-obsessions", "强迫思维是什么", "强迫思维是反复闯入、让人痛苦或不想要的想法、冲动或画面。", "有这些想法不代表你认同它们，也不等于你会照做。"),
            ("bulk-ocd-compulsions", "强迫行为为什么停不下来", "强迫行为通常是为了短暂降低焦虑，但会让循环更难结束。", "理解短期安心和长期维持之间的关系，是改变的第一步。"),
            ("bulk-ocd-checking", "反复检查门锁燃气怎么办", "反复检查常和不确定性恐惧有关，检查越多越难相信自己。", "可以记录检查规则，并在专业指导下逐步减少重复。"),
            ("bulk-ocd-contamination", "怕脏怕污染一定是洁癖吗", "污染相关强迫会带来强烈焦虑和清洗冲动，不只是爱干净。", "如果清洗耗时、伤皮肤或影响生活，就值得求助。"),
            ("bulk-ocd-reassurance", "强迫症为什么总想问别人确认", "寻求确认能暂时安心，但会削弱自己承受不确定的能力。", "可以逐步延迟确认，并练习把焦虑留在可承受范围。"),
            ("bulk-ocd-harm-thoughts", "出现伤害性侵入想法怎么办", "侵入性伤害想法可能非常吓人，但不等于真实意愿。", "如果想法让你痛苦或开始回避生活，应寻求专业评估。"),
            ("bulk-ocd-erp", "ERP 暴露与反应预防是什么", "ERP 是逐步接触触发物并减少强迫反应的治疗方法。", "ERP 需要按层级进行，最好由受训专业人员指导。"),
            ("bulk-ocd-mental-rituals", "脑子里反复默念也算强迫吗", "强迫行为不一定看得见，也可能是心理检查、默念或回想。", "如果这些心理动作让你被困住，也属于需要关注的循环。"),
            ("bulk-ocd-family-response", "家人该不该配合强迫确认", "家人反复配合确认可能短期安抚，长期却维持强迫循环。", "更好的方式是温和支持治疗计划，而不是不断提供保证。"),
            ("bulk-ocd-treatment-expectation", "强迫症治疗会立刻好吗", "OCD 治疗通常需要时间和反复练习，不是一次想通就结束。", "关注可持续的小进步，比追求立刻完全不焦虑更现实。"),
        ),
    },
    {
        "source": "nimh_adhd",
        "category": "self_help",
        "actions": ["把任务拆成 10-15 分钟小块。", "使用外部提醒、清单和可视化时间。", "记录症状出现的多个场景。"],
        "seek_help_when": ["注意力、冲动或组织困难长期影响生活。", "症状从儿童期延续并跨场景出现。", "合并焦虑、抑郁、睡眠或风险行为。"],
        "tags": ["ADHD", "注意力", "执行功能", "冲动"],
        "topics": (
            ("bulk-adhd-inattention", "ADHD 的注意力困难是什么样", "ADHD 的注意力困难常表现为走神、漏细节、难以完成长任务或容易被打断。", "这不等于不努力，常需要外部结构和专业评估。"),
            ("bulk-adhd-hyperactivity", "多动一定会坐不住吗", "多动可能表现为坐不住，也可能在成年人身上表现为内在不安。", "不同年龄和性别的表现可能不同，不能只看刻板印象。"),
            ("bulk-adhd-impulsivity", "ADHD 的冲动表现有哪些", "冲动可能包括插话、难等待、快速决定或难以刹住行为。", "冲动问题如果影响关系、财务或安全，需要认真处理。"),
            ("bulk-adhd-time-blindness", "时间感很差可能和 ADHD 有关吗", "ADHD 相关执行功能困难可能让估时、开始任务和准时变得很难。", "可视化时间、倒计时和提前缓冲比单靠意志更有效。"),
            ("bulk-adhd-task-initiation", "想做但启动不了任务怎么办", "任务启动困难常见于执行功能压力，不一定是懒。", "把任务缩到两分钟版本，降低启动门槛。"),
            ("bulk-adhd-organization", "东西总丢和 ADHD 有关系吗", "物品管理混乱、忘带东西和遗失物品可能是注意与组织困难的表现。", "固定放置点和外部清单能减少对记忆的依赖。"),
            ("bulk-adhd-emotion", "ADHD 会影响情绪调节吗", "ADHD 有时伴随低挫折耐受、情绪来得快或难以刹车。", "情绪问题也可能来自焦虑抑郁，需要综合判断。"),
            ("bulk-adhd-adult", "成年人也会有 ADHD 吗", "ADHD 起始于儿童期，但症状可以持续到成年。", "成年人常因工作、家庭和组织压力增加才明显感到困难。"),
            ("bulk-adhd-school-work", "ADHD 可以申请学习或工作支持吗", "有些人需要课堂、考试、任务管理或工作环境上的合理支持。", "支持方式应结合正式评估和所在机构规则。"),
            ("bulk-adhd-cooccurring", "ADHD 为什么常和焦虑抑郁混在一起", "长期执行困难可能带来自责和压力，焦虑抑郁也会造成注意力问题。", "评估时要同时看注意、情绪、睡眠和生活史。"),
        ),
    },
    {
        "source": "nimh_ptsd",
        "category": "emotion",
        "actions": ["先确认当下环境是否安全。", "用脚踩地、观察物体等方式回到当下。", "记录触发物和身体反应。"],
        "seek_help_when": ["创伤反应持续影响睡眠、关系或工作学习。", "出现闪回、解离、自伤想法或现实危险。", "你正处于持续创伤环境中。"],
        "tags": ["PTSD", "创伤", "闪回", "回避", "警觉"],
        "topics": (
            ("bulk-trauma-normal-reactions", "创伤后有反应是不是正常", "经历创伤后出现害怕、麻木、睡不好或反复想起是常见反应。", "多数人会逐渐恢复，但持续严重影响生活时需要专业支持。"),
            ("bulk-trauma-flashbacks", "闪回是什么感觉", "闪回像是创伤记忆突然闯入，让人感觉事情又在发生。", "闪回时先回到当下环境，比立刻分析原因更重要。"),
            ("bulk-trauma-avoidance", "创伤后为什么会回避相关场景", "回避可以短期减少痛苦，但长期可能限制生活并维持恐惧。", "处理回避需要安全、节奏和专业支持。"),
            ("bulk-trauma-hypervigilance", "总是警觉放松不下来怎么办", "创伤后身体可能长期处于警戒状态，对声音、表情或环境特别敏感。", "这种反应不是矫情，而是威胁系统过度工作。"),
            ("bulk-trauma-sleep", "创伤后睡不好怎么办", "创伤可能带来噩梦、夜间惊醒、入睡困难或不敢睡。", "需要先建立安全感和睡前稳定流程，严重时寻求专业帮助。"),
            ("bulk-trauma-guilt-shame", "创伤后的羞耻和自责怎么理解", "创伤后有人会把责任揽到自己身上，产生强烈羞耻或内疚。", "自责不等于事实，专业支持可帮助重新理解责任和安全。"),
            ("bulk-trauma-children", "孩子经历创伤后可能怎样表现", "孩子的创伤反应可能表现为黏人、退化、噩梦、易怒或游戏中重复事件。", "照护者稳定回应和及时专业支持很重要。"),
            ("bulk-trauma-ongoing", "还在创伤环境里怎么办", "如果危险仍在发生，安全计划比单纯情绪调节更优先。", "应优先联系可信任的人、机构或紧急资源。"),
            ("bulk-trauma-grounding", "创伤触发时稳定练习怎么做", "触发时可以通过外部感官、脚踩地和描述环境帮助大脑回到现在。", "稳定练习不是治疗全部创伤，而是先降低失控感。"),
            ("bulk-trauma-therapy", "创伤治疗一般关注什么", "创伤治疗通常关注安全、触发识别、情绪调节和重新理解创伤经历。", "具体方法和节奏需要由有经验的专业人员评估。"),
        ),
    },
    {
        "source": "medlineplus_insomnia",
        "category": "sleep",
        "actions": ["固定起床时间。", "减少睡前刺激和咖啡因。", "把担心写下来安排到白天处理。"],
        "seek_help_when": ["睡眠问题持续影响白天功能。", "伴随强烈焦虑、低落或创伤反应。", "怀疑身体疾病、药物或其他睡眠障碍影响。"],
        "tags": ["失眠", "睡眠", "睡不着", "早醒"],
        "topics": (
            ("bulk-sleep-hygiene", "睡眠卫生是什么意思", "睡眠卫生是帮助身体形成稳定睡眠节律的一组习惯。", "它包括固定起床时间、减少刺激和让床重新和睡眠建立联系。"),
            ("bulk-sleep-rumination", "睡前反复想事情怎么办", "睡前反刍会提高大脑唤醒，让入睡更困难。", "把担心写下并安排明天处理，可以减少夜间脑内循环。"),
            ("bulk-sleep-early-waking", "总是早醒需要注意什么", "早醒可能和压力、抑郁、作息或身体因素有关。", "如果早醒持续并影响白天状态，应记录并考虑求助。"),
            ("bulk-sleep-nightmares", "频繁噩梦和心理压力有关吗", "噩梦可能和压力、创伤、睡眠不稳或药物等因素相关。", "如果噩梦反复并影响睡眠和白天状态，需要评估原因。"),
            ("bulk-sleep-napping", "白天补觉会影响晚上睡觉吗", "长时间或太晚午睡可能削弱夜间睡意。", "如果失眠明显，白天补觉要短且靠前。"),
            ("bulk-sleep-caffeine", "下午咖啡会影响失眠吗", "咖啡因会延长身体兴奋，可能让入睡困难或睡眠变浅。", "对焦虑或失眠敏感的人尤其需要观察摄入时间。"),
            ("bulk-sleep-bed-association", "躺床上越久越睡不着怎么办", "长期在床上焦虑清醒，会让床和清醒焦虑形成关联。", "可以把床尽量留给睡眠，睡不着时短暂离开做低刺激活动。"),
            ("bulk-sleep-schedule", "周末补觉会打乱作息吗", "周末睡太晚起太晚可能让生物钟更不稳定。", "固定起床时间通常比每天强行早睡更关键。"),
            ("bulk-sleep-screen", "睡前刷手机为什么影响睡眠", "手机内容和互动会提高认知唤醒，让大脑更难降速。", "睡前减少刺激内容比单纯关灯更重要。"),
            ("bulk-sleep-seek-help", "失眠多久需要找医生", "如果失眠持续数周并影响白天功能，就值得联系医疗或心理健康专业人员。", "求助可以帮助排查压力、身体疾病、药物和睡眠障碍。"),
        ),
    },
    {
        "source": "nimh_bpd",
        "category": "relationship",
        "actions": ["先暂停升级中的对话。", "记录触发点、情绪强度和冲动。", "用具体需求代替绝对化指责。"],
        "seek_help_when": ["情绪和关系冲突长期影响生活。", "出现自伤、自杀想法或冲动行为。", "你需要区分创伤、双相、边缘型人格或其他问题。"],
        "tags": ["关系", "情绪调节", "边界", "DBT"],
        "topics": (
            ("bulk-bpd-rejection", "对拒绝特别敏感怎么办", "强烈拒绝敏感可能让人把模糊回应理解成被抛弃。", "先区分事实和解释，有助于避免关系快速升级。"),
            ("bulk-bpd-abandonment", "害怕被抛下为什么这么强烈", "害怕被抛下可能来自关系经验、创伤或情绪调节困难。", "这种感受很真实，但不一定代表对方真的要离开。"),
            ("bulk-bpd-emotion-storm", "情绪来得太猛怎么办", "强烈情绪像浪一样来时，先稳定身体和延迟冲动反应。", "等强度下降后再处理关系问题，通常更安全。"),
            ("bulk-bpd-unstable-relationships", "关系总是忽远忽近怎么理解", "关系不稳定可能和强烈期待、失望和安全感波动有关。", "记录触发点和沟通模式，比只怪自己或对方更有帮助。"),
            ("bulk-bpd-identity", "自我感不稳定是什么", "自我感不稳定可能表现为不知道自己想要什么、价值感随关系变化。", "稳定生活结构和长期支持能帮助逐步建立自我感。"),
            ("bulk-bpd-anger", "控制不住怒火怎么办", "强烈愤怒可能来自被伤害、被拒绝或被误解的感受。", "先暂停、离开现场和降低身体唤醒，比继续争对错更重要。"),
            ("bulk-bpd-dissociation", "情绪强时突然麻木或抽离怎么办", "强烈压力下有人会出现解离感、麻木或像不在现场。", "先用外部感官和安全物体回到当下。"),
            ("bulk-bpd-dbt-skills", "DBT 技能适合什么问题", "DBT 常用于情绪调节、人际冲突和冲动行为管理。", "技能训练不能替代诊断，但可以作为专业治疗的一部分。"),
            ("bulk-relationship-boundary", "边界和冷漠有什么区别", "边界是说明自己能接受什么，不是惩罚或切断所有关系。", "清楚边界能减少猜测、委屈和爆发。"),
            ("bulk-relationship-conflict-timeout", "吵架时暂停是不是逃避", "冲突升级时暂停可以保护沟通窗口，不等于拒绝解决。", "暂停需要约定回来继续谈的时间和方式。"),
        ),
    },
    {
        "source": "nimh_eating",
        "category": "self_help",
        "actions": ["记录饮食限制、暴食、催吐或过度运动频率。", "避免把问题简化成自律失败。", "尽早联系医生或心理健康专业人员。"],
        "seek_help_when": ["饮食、体重或体型想法支配生活。", "出现催吐、极端节食或快速体重变化。", "出现晕厥、胸闷、自伤想法或医疗风险。"],
        "tags": ["饮食障碍", "身体形象", "暴食", "厌食"],
        "topics": (
            ("bulk-eating-restriction", "极端限制进食有什么风险", "极端限制进食可能影响身体和心理健康，不只是减肥方式。", "如果限制越来越严格或伴随恐惧增重，应尽早求助。"),
            ("bulk-eating-binge", "暴食发作是什么", "暴食通常指短时间大量进食并伴随失控感和明显痛苦。", "暴食不是单纯馋或没自制力，常和情绪、羞耻和压力有关。"),
            ("bulk-eating-purging", "催吐或泻药控制体重危险吗", "催吐和滥用泻药可能带来严重身体风险。", "这类行为出现时应优先联系医疗和心理健康专业人员。"),
            ("bulk-eating-body-checking", "反复检查体重体型怎么办", "频繁称重、照镜子或捏身体可能加重身体形象焦虑。", "可以逐步减少检查频率，并关注身体功能而非单一数字。"),
            ("bulk-eating-arfid", "ARFID 和挑食有什么不同", "ARFID 涉及对食物种类或摄入量的严重限制，并造成营养或功能影响。", "它不一定以体重恐惧为核心，但同样需要专业评估。"),
            ("bulk-eating-overexercise", "过度运动也可能是警讯吗", "过度运动如果用于补偿进食或控制体重，可能是饮食障碍相关信号。", "运动开始压倒健康和生活时，需要重新评估。"),
            ("bulk-eating-medical-risk", "饮食障碍为什么需要医学监测", "饮食障碍可能影响心脏、电解质、骨骼、胃肠和整体身体状态。", "心理支持之外，医疗监测常常很重要。"),
            ("bulk-eating-body-image", "身体形象困扰怎么理解", "身体形象困扰会让人把价值感强烈绑定体重和外貌。", "练习减少身体检查和比较，是恢复的一部分。"),
            ("bulk-eating-family-support", "家人如何支持饮食障碍恢复", "家人支持应减少指责和体型评论，帮助建立治疗和安全饮食环境。", "青少年饮食障碍尤其需要家庭和专业系统参与。"),
            ("bulk-eating-cooccurring", "饮食障碍为什么常伴随焦虑抑郁", "饮食障碍常和焦虑、抑郁、羞耻、自我价值感和控制感交织。", "治疗时需要同时关注饮食行为和共病心理状态。"),
        ),
    },
    {
        "source": "nimh_psychosis",
        "category": "safety",
        "actions": ["记录异常体验的时间、频率和影响。", "减少争辩真实与否，优先保持安全和支持。", "尽快联系专业人员评估。"],
        "seek_help_when": ["出现幻听、妄想或明显现实感混乱。", "异常体验影响学习、工作、睡眠或安全。", "伴随自伤、伤人风险或无法照顾自己。"],
        "tags": ["精神病性症状", "幻觉", "妄想", "现实感"],
        "topics": (
            ("bulk-psychosis-basics", "精神病性症状是什么", "精神病性症状指思维和感知受到影响，现实判断变得困难。", "这类体验需要尽早专业评估，而不是靠意志硬扛。"),
            ("bulk-psychosis-hallucination", "听到别人听不到的声音怎么办", "听到不存在的声音可能是幻听，也可能和睡眠、物质或压力有关。", "如果反复出现或让你害怕，应联系专业人员。"),
            ("bulk-psychosis-delusion", "坚信被害或被监视需要注意什么", "强烈被害感或被监视感如果难以被证据动摇，可能涉及妄想体验。", "优先保证安全，避免独自处理或激烈争辩。"),
            ("bulk-psychosis-disorganized", "说话思路很乱可能说明什么", "思维紊乱可能表现为话题跳跃、难以组织表达或别人难理解。", "如果变化明显且影响生活，需要专业评估。"),
            ("bulk-psychosis-early-warning", "早期精神病性问题有哪些预警", "社交退缩、学习工作下降、可疑感增加、感知异常和睡眠紊乱都值得关注。", "越早获得支持，越有利于恢复功能。"),
            ("bulk-psychosis-family-help", "家人发现异常体验该怎么做", "家人应保持冷静、减少责备，关注安全和专业帮助。", "不要强行争辩对错，可以表达关心并协助就医。"),
            ("bulk-schizophrenia-symptoms", "精神分裂症有哪些症状类别", "精神分裂症症状可包括精神病性症状、动机和情感表达下降、认知困难等。", "诊断需要专业人员综合评估。"),
            ("bulk-schizophrenia-treatment", "精神分裂症治疗通常包括什么", "治疗常关注药物、心理社会支持、家庭教育和学习工作功能恢复。", "治疗方案需要医生和多学科团队制定。"),
            ("bulk-psychosis-substance", "物质使用会诱发精神病性体验吗", "某些物质或停用过程可能引发或加重异常感知和现实判断困难。", "出现这类情况应尽快联系医疗帮助。"),
            ("bulk-psychosis-crisis", "异常体验伴随危险想法怎么办", "如果幻觉、妄想或混乱伴随自伤、伤人或无法自我照顾，需要立即求助。", "此时现实安全优先于普通知识问答。"),
        ),
    },
    {
        "source": "nimh_autism",
        "category": "self_help",
        "actions": ["记录沟通、感官和日常功能中的具体困难。", "用清楚、具体和可预测的方式降低压力。", "需要时寻找发展行为或心理健康专业评估。"],
        "seek_help_when": ["社交沟通、学习工作或生活自理受到长期影响。", "感官压力导致明显痛苦或回避。", "伴随焦虑、抑郁、自伤或安全风险。"],
        "tags": ["自闭谱系", "ASD", "社交沟通", "感官"],
        "topics": (
            ("bulk-autism-basics", "自闭谱系是什么", "自闭谱系涉及社会沟通、互动方式、限制性兴趣和重复行为的差异。", "它是谱系状态，不同人的能力、需求和挑战差异很大。"),
            ("bulk-autism-social-communication", "自闭谱系的社交沟通困难是什么", "社交沟通困难可能表现为难读懂暗示、眼神、语气或互动规则。", "这不是不礼貌，很多时候需要更清楚直接的信息。"),
            ("bulk-autism-repetitive", "重复行为和固定兴趣怎么理解", "重复行为、固定兴趣或固定流程可能带来安全感和可预测性。", "当它们影响功能或引发冲突时，可以逐步调整环境支持。"),
            ("bulk-autism-sensory", "感官敏感为什么会很累", "声音、光线、触感或气味过载可能让人迅速疲惫或崩溃。", "减少刺激和预留恢复空间很重要。"),
            ("bulk-autism-meltdown", "崩溃和发脾气有什么区别", "感官或情绪过载下的崩溃不是故意操控，而是调节能力超载。", "处理重点是降低刺激和恢复安全，而不是讲道理。"),
            ("bulk-autism-masking", "长期伪装正常为什么很耗竭", "为了适应社交而长期压抑真实反应，可能带来疲惫和焦虑。", "识别伪装成本有助于安排恢复和支持。"),
            ("bulk-autism-adult-assessment", "成年人还可以评估自闭谱系吗", "自闭谱系通常早期出现，但有些人到成年才意识到长期模式。", "专业评估会结合发展史、当前功能和多方面信息。"),
            ("bulk-autism-anxiety", "自闭谱系为什么常伴随焦虑", "不可预测环境、感官过载和社交误解都可能增加焦虑。", "支持焦虑时需要同时考虑环境调整和沟通方式。"),
            ("bulk-autism-school-work", "自闭谱系在学校或工作中需要什么支持", "清晰规则、可预测安排、感官调整和明确沟通常能降低压力。", "具体支持应结合个人需要和机构条件。"),
            ("bulk-autism-strengths", "自闭谱系只有困难吗", "自闭谱系也可能伴随专注、细节观察、诚实直接或深度兴趣等优势。", "支持应同时看见困难、需求和优势。"),
        ),
    },
    {
        "source": "nimh_suicide",
        "category": "safety",
        "actions": ["立刻联系可信任的人。", "远离可能伤害自己的工具或场景。", "紧急时拨打当地紧急电话或危机热线。"],
        "seek_help_when": ["谈到想死、计划或寻找方法。", "感到无望、被困住、是负担或痛苦无法承受。", "行为突然变化、告别、赠送物品或风险行为增加。"],
        "tags": ["自杀预警", "危机", "安全", "求助"],
        "topics": (
            ("bulk-suicide-warning-talk", "说想死是需要认真对待的信号吗", "谈到想死、想结束生命或成为负担，都需要认真对待。", "即使对方像是在试探，也应优先联系现实支持。"),
            ("bulk-suicide-hopeless", "强烈无望感为什么危险", "无望、被困住或觉得没有理由活下去，可能是危机预警。", "这类状态需要尽快让现实中的人知道。"),
            ("bulk-suicide-plan", "有计划或找方法时怎么办", "一旦开始计划或寻找伤害自己的方法，风险会明显升高。", "不要独处，立刻联系可信任的人或紧急服务。"),
            ("bulk-suicide-goodbye", "突然告别或送东西要注意什么", "告别、赠送重要物品或整理后事可能是严重预警。", "发现这些变化时应尽快介入和求助。"),
            ("bulk-suicide-risk-behavior", "危险行为突然增加说明什么", "鲁莽驾驶、物质使用增加或极端冒险可能和危机状态有关。", "需要关注近期是否同时有绝望、痛苦或计划信号。"),
            ("bulk-suicide-mood-shift", "情绪突然变平静也可能危险吗", "严重低落后突然异常平静，有时可能意味着已经做出危险决定。", "如果伴随告别或计划，应立即求助。"),
            ("bulk-suicide-support-ask", "可以直接问对方是不是想自杀吗", "直接、温和地询问自杀想法不会把想法种进去，反而可能打开求助窗口。", "问完后要倾听，并帮助连接现实支持。"),
            ("bulk-suicide-stay", "别人说要自杀时能答应保密吗", "涉及生命安全时不能承诺保密。", "应联系可信任成年人、家人、专业人员或紧急服务。"),
            ("bulk-suicide-988", "危机热线适合什么时候用", "当人处在自杀危机或强烈情绪痛苦中，危机热线可提供即时支持。", "不同地区号码不同，应使用当地可用的紧急和危机资源。"),
            ("bulk-suicide-aftercare", "危机缓解后还需要做什么", "危机缓解后仍需要安全计划、现实支持和专业跟进。", "一次稳定不代表问题结束，后续支持能降低复发风险。"),
        ),
    },
)


def _bulk_article(group: dict[str, object], topic: tuple[str, str, str, str]) -> dict[str, object]:
    slug, title, summary, focus = topic
    source = BULK_SOURCE_PROFILES[str(group["source"])]
    tags = list(group["tags"])
    return {
        "slug": slug,
        "title": title,
        "category": group["category"],
        "audience": "all",
        "summary_30s": summary,
        "explanation_3min": f"{focus} 这条知识用于心理健康科普和自助整理，不等同于诊断、治疗或用药建议。判断是否达到临床问题，需要结合持续时间、严重程度、功能影响和专业评估。",
        "advanced_text": source["source_note"],
        "common_misunderstandings": ["这不是用来给自己或别人贴标签。", "单一表现不能代替专业评估。"],
        "actions": list(group["actions"]),
        "seek_help_when": list(group["seek_help_when"]),
        "tags": [*tags, title],
        "source_key": source["source_key"],
        "source_url": source["source_url"],
        "license": source["license"],
    }


BULK_COMMON_TOPIC_ARTICLES = [
    _bulk_article(group, topic)
    for group in BULK_TOPIC_GROUPS
    for topic in group["topics"]
][:100]

EXPANDED_SEED_ARTICLES.extend(BULK_COMMON_TOPIC_ARTICLES)
